[defwin]
title = DefWin
help = Advanced window features. Works only on Windows, with some only having an effect on Windows 11.

lock_aspect_ratio.type = bool
lock_aspect_ratio.default = 0
lock_aspect_ratio.help = Lock the aspect ratio of the window on resize to the resolution in game.project.

use_dark_mode_preference.type = bool
use_dark_mode_preference.default = 0
use_dark_mode_preference.help = If enabled, will apply the preference of the current user for dark or light mode to the window.

set_clear_transparent.type = bool
set_clear_transparent.default = 0
set_clear_transparent.help = If enabled, the clear color of the window will be transparent.

rtl_layout.label = Right-to-Left Layout
rtl_layout.type = bool
rtl_layout.default = 0
rtl_layout.help = If enabled, window bar layout is right-to-left.

disable_border.type = bool
disable_border.default = 0
disable_border.help = If enabled, window border is hidden.

minimum_width.type = integer
minimum_width.default = 0
minimum_width.help = The minimum width that the window will be forced to on resize.

minimum_height.type = integer
minimum_height.default = 0
minimum_height.help = The minimum height that the window will be forced to on resize.

rounded_corners.type = string
rounded_corners.default = DEFAULT
rounded_corners.help = Rounding mode of the window corners. Only on Windows 11.
rounded_corners.options = DEFAULT: Default, ROUND: Fully rounded, ROUNDSMALL: Slightly rounded, DONOTROUND: Not rounded